steps:
  - id: 'branch name'
    name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "*******************"
        echo "$BRANCH_NAME"
        echo "*******************"

  - id: 'terraform init'
    name: 'hashicorp/terraform:0.13.3'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform init
        terraform workspace select $BRANCH_NAME || terraform workspace new $BRANCH_NAME
        echo "workspace selected $BRANCH_NAME"
        terraform state list

  - id: 'terraform validate'
    name: 'hashicorp/terraform:0.13.3'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform workspace select $BRANCH_NAME
        echo "workspace selected $BRANCH_NAME"
        terraform validate
     waitFor: ['terraform init']

  - id: 'terraform plan'
    name: 'hashicorp/terraform:0.13.3'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform workspace select $BRANCH_NAME
        echo "workspace selected $BRANCH_NAME"
        terraform plan

  - id: 'terraform apply'
    name: 'hashicorp/terraform:0.13.3'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform workspace select $BRANCH_NAME
        echo "workspace selected $BRANCH_NAME"
        terraform apply -auto-approve

timeout: 1200s
