region                         = "europe-west2"
zone                           = "europe-west2-a"
composer_environment_name      = "my-composer-env"
cloud_composer_service_account = "composer-env-account"
composer_repository_name       = "project-demo-code"
repo_owner                     = "vikramshinde12"
slack_webhook_url              = "https://hooks.slack.com/services/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"